// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Describe resolves paths — the picker's, or ones dropped onto the window —
 * into entries the send list can show sizes for. Paths that can no longer be
 * read are dropped rather than failing the whole batch: a dropped file may be
 * gone by the time this runs, and one bad path should not discard the rest.
 */
export function Describe(paths: string[] | null): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(3517517302, paths);
}

/**
 * OpenPath opens a file or folder with the OS default handler
 * (Finder/Explorer/xdg-open).
 */
export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1363948864, path);
}

/**
 * SelectFiles opens a native file picker and returns the selected files.
 */
export function SelectFiles(): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(3388695362);
}
