// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileEntry is one item queued for sending.
 */
export interface FileEntry {
    "path": string;
    "name": string;

    /**
     * Size in bytes — for a directory, the sum of everything inside it.
     */
    "size": number;
    "isDir": boolean;
}

/**
 * TransferStats is the payload of croc:send:progress and croc:recv:progress.
 */
export interface TransferStats {
    "percent": number;
    "sent": number;
    "total": number;

    /**
     * Bps is the smoothed transfer rate; 0 until a rate can be measured.
     */
    "bps": number;

    /**
     * ETA is the estimated number of seconds left, -1 while unknown.
     */
    "eta": number;
}
