[package]
name = "floppy"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "floppy_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
specta = "2.0.0-rc"
specta-typescript = "0.0"
tauri-specta = { version = "2.0.0-rc", features = ["derive", "typescript"] }
iroh = "1.0.3"
iroh-blobs = "0.103.0"
n0-future = "0.3.2"
anyhow = "1.0.104"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"
dirs = "6.0.0"
tracing = "0.1.44"
tauri-plugin-dialog = "2.7.2"
spake2 = "0.4.0"
chacha20poly1305 = { version = "0.11.0", features = ["getrandom", "rand_core"] }
hkdf = "0.13.0"
sha2 = "0.11.0"
base64 = "0.23.0"
tokio-tungstenite = { version = "0.30.0", features = ["rustls-tls-webpki-roots"] }
getrandom = "0.4.3"
futures-util = "0.3.33"
ed25519-dalek = "3.0.0"
x25519-dalek = { version = "3.0.0", features = ["static_secrets"] }
hex = "0.4.3"

[dev-dependencies]
tempfile = "3.27.0"

