// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CrocService runs croc transfers in-process with the library's context-aware
 * client (croc.NewCtx): cancelling the context aborts the transfer and tells
 * the peer. No worker processes involved — which is also what keeps mobile
 * targets possible, where an app cannot re-exec itself. Progress is reported
 * to the frontend via events: croc:code, croc:send:progress,
 * croc:recv:progress, croc:sent, croc:received, croc:error.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from '@wailsio/runtime'

/**
 * CancelReceive aborts a running receive transfer. A partially received file
 * may remain in the destination folder (croc reuses it to resume).
 */
export function CancelReceive(): $CancellablePromise<void> {
	return $Call.ByID(329269001)
}

/**
 * CancelSend aborts a running send transfer.
 */
export function CancelSend(): $CancellablePromise<void> {
	return $Call.ByID(1762729354)
}

/**
 * Receive starts a receive transfer for the given code phrase; files are
 * saved to the user's Downloads folder. Progress is emitted as
 * croc:recv:progress (percent), completion as croc:received (with the
 * destination directory as payload), failure as croc:error.
 */
export function Receive(code: string): $CancellablePromise<void> {
	return $Call.ByID(2115431883, code)
}

/**
 * Send starts a send transfer for the given paths and returns immediately.
 * The generated code phrase is emitted as a croc:code event, progress as
 * croc:send:progress (percent), successful completion as croc:sent, failure
 * as croc:error.
 */
export function Send(paths: string[] | null): $CancellablePromise<void> {
	return $Call.ByID(1729625572, paths)
}
