// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenPath opens a file or folder with the OS default handler
 * (Finder/Explorer/xdg-open).
 */
export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1363948864, path);
}

/**
 * SelectFiles opens a native file picker and returns absolute paths
 * of the selected files.
 */
export function SelectFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3388695362);
}
