// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../floppy/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "croc:code": string;
            "croc:error": string;
            "croc:received": string;
            "croc:recv:progress": main$0.TransferStats;
            "croc:send:progress": main$0.TransferStats;
            "croc:sent": string;
            "files-dropped": string[] | null;
        }
    }
}
