// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../../floppy/internal/services/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "croc:code": services$0.CodeEvent;
            "croc:error": services$0.ErrorEvent;
            "croc:received": services$0.DoneEvent;
            "croc:recv:progress": services$0.ProgressEvent;
            "croc:send:progress": services$0.ProgressEvent;
            "croc:sent": services$0.DoneEvent;
            "files-dropped": string[] | null;
            "pairing:accepted": services$0.PairingStatusEvent;
            "pairing:declined": services$0.PairingStatusEvent;
            "pairing:error": services$0.PairingErrorEvent;
            "pairing:offer": services$0.PairingOfferEvent;
        }
    }
}
