// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CrocService is the Wails adapter around transfer.Manager: it exposes the
 * manager's methods as bindings and translates its events into the frontend
 * event vocabulary. No transfer logic lives here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CancelReceive aborts the running receive; a partially received file stays
 * in the per-code folder, and retrying the same code resumes from it.
 */
export function CancelReceive(): $CancellablePromise<void> {
    return $Call.ByID(1476844187);
}

/**
 * CancelSend aborts the running send, returning immediately (the unwind is
 * absorbed by the next transfer).
 */
export function CancelSend(): $CancellablePromise<void> {
    return $Call.ByID(1894710452);
}

/**
 * Receive starts a receive transfer for the given code phrase and returns
 * its transfer ID; files land in ~/Downloads/<code>/.
 */
export function Receive(code: string): $CancellablePromise<string> {
    return $Call.ByID(3225367265, code);
}

/**
 * Send starts a send transfer for the given paths and returns its transfer
 * ID; the code phrase follows as a croc:code event.
 */
export function Send(paths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3652812786, paths);
}
