// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodeEvent is the payload of croc:code.
 */
export interface CodeEvent {
    "id": string;
    "kind": string;
    "code": string;
}

/**
 * DeviceInfo is a trusted device as shown to the frontend.
 */
export interface DeviceInfo {
    "fingerprint": string;
    "name": string;
}

/**
 * DoneEvent is the payload of croc:sent and croc:received; Dest is set for
 * receives only.
 */
export interface DoneEvent {
    "id": string;
    "kind": string;
    "dest"?: string;
}

/**
 * ErrorEvent is the payload of croc:error. Code is machine-readable
 * ("send_failed" | "receive_failed"), Message human-readable.
 */
export interface ErrorEvent {
    "id": string;
    "kind": string;
    "code": string;
    "message": string;
}

/**
 * FileEntry is one item queued for sending.
 */
export interface FileEntry {
    "path": string;
    "name": string;

    /**
     * Size in bytes — for a directory, the sum of everything inside it.
     */
    "size": number;
    "isDir": boolean;
}

/**
 * PairingErrorEvent is the payload of pairing:error.
 */
export interface PairingErrorEvent {
    "transferId": string;
    "code": string;
    "message": string;
}

/**
 * PairingOfferEvent is the payload of pairing:offer — everything the modal needs.
 */
export interface PairingOfferEvent {
    "transferId": string;
    "fromName": string;
    "fromFingerprint": string;
    "fileCount": number;
    "totalBytes": number;
}

/**
 * PairingPreview is what the pairing UI shows before a device is trusted: the
 * peer's fingerprint and the SAS both screens must match. Computing the SAS
 * needs the private key, so it lives here, never in the frontend.
 */
export interface PairingPreview {
    "fingerprint": string;
    "sas": string;
}

/**
 * PairingStatusEvent is the payload of pairing:accepted and pairing:declined.
 */
export interface PairingStatusEvent {
    "transferId": string;
}

/**
 * ProgressEvent is the payload of croc:send:progress and croc:recv:progress.
 */
export interface ProgressEvent {
    "id": string;
    "kind": string;
    "percent": number;
    "sent": number;
    "total": number;

    /**
     * Bps is the smoothed transfer rate; 0 until a rate can be measured.
     */
    "bps": number;

    /**
     * ETA is the estimated number of seconds left, -1 while unknown.
     */
    "eta": number;

    /**
     * File is the name of the file currently moving, FileIndex its 1-based
     * place among FileCount files.
     */
    "file": string;
    "fileIndex": number;
    "fileCount": number;
}
