// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PairingService is the trusted-device Wails adapter. It owns the device
 * identity and trust store, talks to the rendezvous broker, and turns accepted
 * offers into coded transfers on the shared Manager (via CrocService). The
 * croc/transfer core is untouched — this service only decides *what code* to
 * run and *when*.
 * 
 * Desktop-first slice: an incoming offer surfaces as a pairing:offer event that
 * the frontend renders as an Accept/Decline modal (the app is assumed open).
 * The OS interactive notification that wakes a closed app is the later mobile
 * layer, on this same protocol.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Accept confirms an incoming offer: derive the code, start receiving, and tell
 * the sender to begin. No code or passphrase is entered by the user.
 */
export function Accept(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(492542427, transferID);
}

/**
 * Decline rejects an incoming offer and tells the sender.
 */
export function Decline(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(4096786631, transferID);
}

/**
 * Identity returns this device's public identity, encoded for display/QR.
 */
export function Identity(): $CancellablePromise<string> {
    return $Call.ByID(369257033);
}

/**
 * PreviewPairing decodes an encoded peer identity and returns its fingerprint
 * and the shared SAS for the compare step. It does not trust the device — Trust
 * does that once the user confirms the codes match.
 */
export function PreviewPairing(encoded: string): $CancellablePromise<$models.PairingPreview> {
    return $Call.ByID(4012706627, encoded);
}

/**
 * SendTo offers paths to a trusted device. It returns the transfer id; the
 * actual send only starts once that device accepts (pairing:accepted) — or is
 * reported via pairing:declined / pairing:error.
 */
export function SendTo(fingerprint: string, paths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1620649728, fingerprint, paths);
}

/**
 * Trust records a peer as trusted after the user confirmed the SAS. name is the
 * display label.
 */
export function Trust(encoded: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1266878235, encoded, name);
}

/**
 * TrustedDevices lists the devices this install trusts.
 */
export function TrustedDevices(): $CancellablePromise<$models.DeviceInfo[] | null> {
    return $Call.ByID(1800376557);
}

/**
 * Untrust removes a device by fingerprint — the desktop stand-in for revocation.
 */
export function Untrust(fingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(3179053490, fingerprint);
}
