// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	send: (paths: string[]) => typedError<null, string>(__TAURI_INVOKE("send", { paths })),
	receive: (code: string) => typedError<null, string>(__TAURI_INVOKE("receive", { code })),
	cancelSend: () => typedError<null, string>(__TAURI_INVOKE("cancel_send")),
	cancelReceive: () => typedError<null, string>(__TAURI_INVOKE("cancel_receive")),
	/**  Quick one-off share over a human code phrase (code-phrase-share). */
	quickShare: (paths: string[]) => typedError<null, string>(__TAURI_INVOKE("quick_share", { paths })),
	describe: (paths: string[]) => typedError<FileEntry[], string>(__TAURI_INVOKE("describe", { paths })),
	openPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_path", { path })),
	identity: () => typedError<string, string>(__TAURI_INVOKE("identity")),
	trustedDevices: () => typedError<DeviceInfo[], string>(__TAURI_INVOKE("trusted_devices")),
	previewPairing: (encoded: string) => typedError<PairingPreview, string>(__TAURI_INVOKE("preview_pairing", { encoded })),
	trust: (encoded: string, name: string) => typedError<null, string>(__TAURI_INVOKE("trust", { encoded, name })),
	untrust: (fingerprint: string) => typedError<null, string>(__TAURI_INVOKE("untrust", { fingerprint })),
	/**
	 *  Create a one-sided pairing link (show as text/QR). Whoever opens it pairs
	 *  with this device in a single step.
	 */
	createPairLink: () => typedError<string, string>(__TAURI_INVOKE("create_pair_link")),
	/**  Open a pairing link from another device: trust it and become mutually paired. */
	openPairLink: (link: string) => typedError<null, string>(__TAURI_INVOKE("open_pair_link", { link })),
	accept: (transferId: string) => typedError<null, string>(__TAURI_INVOKE("accept", { transferId })),
	decline: (transferId: string) => typedError<null, string>(__TAURI_INVOKE("decline", { transferId })),
	sendTo: (fingerprint: string, paths: string[]) => typedError<null, string>(__TAURI_INVOKE("send_to", { fingerprint, paths })),
};

/** Events */
export const events = {
	codeEvent: makeEvent<CodeEvent>("code-event"),
	doneEvent: makeEvent<DoneEvent>("done-event"),
	errorEvent: makeEvent<ErrorEvent>("error-event"),
	pairingAccepted: makeEvent<PairingAccepted>("pairing-accepted"),
	pairingDeclined: makeEvent<PairingDeclined>("pairing-declined"),
	pairingError: makeEvent<PairingError>("pairing-error"),
	pairingOfferEvent: makeEvent<PairingOfferEvent>("pairing-offer-event"),
	pairingPaired: makeEvent<PairingPaired>("pairing-paired"),
	progressEvent: makeEvent<ProgressEvent>("progress-event"),
};

/* Types */
/**  The code/ticket to display for a send (emitted once, at the start). */
export type CodeEvent = {
	id: string,
	kind: TransferKind,
	code: string,
};

export type DeviceInfo = {
	fingerprint: string,
	name: string,
};

/**  Transfer finished. `dest` is the save path on a receive, empty on a send. */
export type DoneEvent = {
	id: string,
	kind: TransferKind,
	dest: string,
};

/**  Transfer failed. `message` is human text; `code` is machine-readable. */
export type ErrorEvent = {
	id: string,
	kind: TransferKind,
	code: string,
	message: string,
};

export type FileEntry = {
	path: string,
	name: string,
	size: number,
	isDir: boolean,
};

/**  The peer accepted a trusted-device offer. */
export type PairingAccepted = null;

/**  The peer declined a trusted-device offer. */
export type PairingDeclined = null;

/**  A pairing/signalling error surfaced as a toast. */
export type PairingError = {
	message: string,
};

/**  A verified incoming trusted-device offer awaiting accept/decline. */
export type PairingOfferEvent = {
	transferId: string,
	fromName: string,
	fileCount: number,
	totalBytes: number,
};

/**  A one-sided pairing completed; `name` is the newly trusted device. */
export type PairingPaired = {
	name: string,
};

export type PairingPreview = {
	fingerprint: string,
	sas: string,
	name: string,
};

/**  Byte/file progress for the active transfer. */
export type ProgressEvent = {
	id: string,
	kind: TransferKind,
	percent: number,
	file: string,
	fileIndex: number,
	fileCount: number,
	sent: number,
	total: number,
	bps: number,
	eta: number,
};

/**  Which side of a transfer an event belongs to. Serializes as "send"/"receive". */
export type TransferKind = "send" | "receive";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

