// The frontend↔core bridge. `bindings.ts` is generated by tauri-specta (never
// hand-edited); it carries the whole typed contract — `commands`, `events`, and
// every shared type. This module re-exports it, adds the runtime shims, and
// wraps each command so a failed `Result` throws (the UI is written around
// try/catch and `describeError(String(e))`) instead of returning a status union.

import { commands } from './bindings'

export * from './bindings'
export { Clipboard, Window } from './runtime'

/** Unwrap a tauri-specta `Result`: return the data, or throw the error string. */
async function ok<T>(p: Promise<{ status: 'ok'; data: T } | { status: 'error'; error: string }>): Promise<T> {
	const r = await p
	if (r.status === 'error') throw new Error(r.error)
	return r.data
}

// Transfer
export const Send = (paths: string[]) => ok(commands.send(paths))
export const Receive = (code: string) => ok(commands.receive(code))
export const CancelSend = () => ok(commands.cancelSend())
export const CancelReceive = () => ok(commands.cancelReceive())
export const QuickShare = (paths: string[]) => ok(commands.quickShare(paths))

// Files (the picker uses @tauri-apps/plugin-dialog `open()` directly)
export const Describe = (paths: string[]) => ok(commands.describe(paths))
export const OpenPath = (path: string) => ok(commands.openPath(path))
/** Reap the sandbox copies made for a mobile send queue (a no-op on desktop). */
export const ClearInputCache = () => ok(commands.clearInputCache())

// Pairing
export const Identity = () => ok(commands.identity())
export const TrustedDevices = () => ok(commands.trustedDevices())
export const Untrust = (fingerprint: string) => ok(commands.untrust(fingerprint))
export const ConfirmPair = (fingerprint: string, name: string) => ok(commands.confirmPair(fingerprint, name))
export const DismissPair = (fingerprint: string) => ok(commands.dismissPair(fingerprint))
export const RenameDevice = (fingerprint: string, name: string) =>
	ok(commands.renameDevice(fingerprint, name))
export const ShowPairCode = () => ok(commands.showPairCode())
export const RedeemPairCode = (code: string, via: string) => ok(commands.redeemPairCode(code, via))
export const SelfName = () => ok(commands.selfName())
export const SetSelfName = (name: string) => ok(commands.setSelfName(name))
export const Accept = (transferId: string) => ok(commands.accept(transferId))
export const Decline = (transferId: string) => ok(commands.decline(transferId))
export const SendTo = (fingerprint: string, paths: string[]) => ok(commands.sendTo(fingerprint, paths))
