// Runtime bits the generated bindings don't cover: window controls and the
// clipboard. Typed commands and events come from `./bindings` (generated by
// tauri-specta) — this file is only the handful of Tauri runtime APIs the UI
// touches directly.

import { writeText } from '@tauri-apps/plugin-clipboard-manager'
import { getCurrentWindow } from '@tauri-apps/api/window'

export const Window = {
	Minimise: () => getCurrentWindow().minimize(),
	ToggleMaximise: () => getCurrentWindow().toggleMaximize(),
	Close: () => getCurrentWindow().close()
}

/**
 * The OS clipboard, via the clipboard-manager plugin rather than
 * `navigator.clipboard`, which needs a secure context and permission the
 * webview does not always grant.
 */
export const Clipboard = {
	SetText: (text: string) => writeText(text)
}
